In [1]:
import numpy as np
import pandas as pd

In [2]:
file=r'C:\Users\chirag\Desktop\ML IITK\KNN,NB,SVM\DATA\review_corpus.csv'

In [4]:
td=pd.read_csv(file,encoding='latin-1')

In [5]:
td.head()

text        label
0   Stuning even for the non-gamer: This sound tr...  __label__2 
1   The best soundtrack ever to anything.: I'm re...  __label__2 
2   Amazing!: This soundtrack is my favorite musi...  __label__2 
3   Excellent Soundtrack: I truly like this sound...  __label__2 
4   Remember, Pull Your Jaw Off The Floor After H...  __label__2

In [6]:
td['label'].value_counts()

__label__1     5097
__label__2     4903
Name: label, dtype: int64

In [7]:
td['text'][0]

' Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate video game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^'

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
tfidf=TfidfVectorizer(analyzer='word',stop_words='english',min_df=0.01,max_df=0.6)

In [13]:
tfidf.fit(td['text'])

TfidfVectorizer(max_df=0.6, min_df=0.01, stop_words='english')

In [14]:
tfidf_data=tfidf.transform(td['text'])

In [15]:
tfidf_data.shape

(10000, 532)

In [16]:
tfidf_data

<10000x532 sparse matrix of type '<class 'numpy.float64'>'
	with 147494 stored elements in Compressed Sparse Row format>

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC

In [19]:
knn=KNeighborsClassifier(n_neighbors=100)
nb=MultinomialNB()
svm=SVC()

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(knn,tfidf_data,td['label'],cv=10,scoring='accuracy',n_jobs=-1)

array([0.718, 0.781, 0.717, 0.707, 0.713, 0.704, 0.722, 0.701, 0.73 ,
       0.746])

In [22]:
cross_val_score(nb,tfidf_data,td['label'],cv=10,scoring='accuracy',n_jobs=-1)

array([0.797, 0.81 , 0.774, 0.779, 0.788, 0.778, 0.797, 0.777, 0.803,
       0.803])

In [23]:
cross_val_score(svm,tfidf_data,td['label'],cv=10,scoring='accuracy',n_jobs=-1)

array([0.826, 0.829, 0.802, 0.803, 0.797, 0.791, 0.804, 0.786, 0.814,
       0.824])

In [ ]:
ll